# Generated by Django 4.2.6 on 2023-10-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer_Reg',
            fields=[
                ('User_Id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Address', models.TextField(max_length=200)),
                ('Phone_No', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=15)),
                ('Id_Proof', models.ImageField(blank=True, null=True, upload_to='Id_Proof/')),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FarmHouse_Reg',
            fields=[
                ('User_Id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Address', models.TextField(max_length=200)),
                ('Phone_No', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=15)),
                ('Id_Proof', models.ImageField(blank=True, null=True, upload_to='Id_Proof/')),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('User_Id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Address', models.TextField(max_length=200)),
                ('Phone_No', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=15)),
                ('User_Type', models.IntegerField(default=2)),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
    ]
