# Generated by Django 4.2.6 on 2023-10-09 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='User_Register',
        ),
    ]
