# Generated by Django 4.2.6 on 2023-10-10 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_rename_register_user_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Register',
            new_name='User_Reg',
        ),
    ]
