# Generated by Django 4.2.6 on 2023-10-10 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_rename_user_register_user_reg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer_reg',
            old_name='User_Id',
            new_name='Farmer_Id',
        ),
        migrations.RenameField(
            model_name='farmhouse_reg',
            old_name='User_Id',
            new_name='FarmHouse_Id',
        ),
    ]
