# Generated by Django 4.2.6 on 2023-10-11 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_rename_user_id_farmer_reg_farmer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_reg',
            name='Status',
        ),
    ]
