# Generated by Django 4.2.6 on 2023-10-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_remove_user_reg_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer_reg',
            name='User_Type',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='farmhouse_reg',
            name='User_Type',
            field=models.IntegerField(default=4),
        ),
    ]
