# Generated by Django 4.2.6 on 2023-10-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_farmer_reg_user_type_farmhouse_reg_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Category_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Category_Name', models.CharField(max_length=100)),
            ],
        ),
    ]
