# Generated by Django 4.2.6 on 2023-10-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
