# Generated by Django 4.2.6 on 2023-10-24 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('Cart_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.BooleanField(default=True)),
                ('Count', models.IntegerField(default=0)),
                ('User_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.user_reg')),
            ],
        ),
        migrations.CreateModel(
            name='Cart_Items',
            fields=[
                ('Item_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Qty', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('Cart_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.cart')),
                ('Farmers_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.farmer_reg')),
                ('Product_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.product')),
                ('User_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.user_reg')),
            ],
        ),
    ]
