# Generated by Django 4.2.6 on 2023-10-24 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_cart_cart_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_items',
            old_name='Cart_Id',
            new_name='Carts_Id',
        ),
    ]
