# Generated by Django 4.2.6 on 2023-10-28 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_rename_farmers_id_cart_items_farmers_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='delivery_agent',
            fields=[
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('id_proof', models.ImageField(blank=True, null=True, upload_to='agent_id/')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.IntegerField(default=4)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('pickup_date', models.DateField()),
                ('pickup_status', models.BooleanField(default=False)),
                ('deliver_status', models.BooleanField(default=False)),
                ('agents_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.delivery_agent')),
                ('cart_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.cart_items')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.user_reg')),
            ],
        ),
    ]
