# Generated by Django 4.2.6 on 2023-11-02 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_delivery_agent_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='govt_policies',
            fields=[
                ('policy_id', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='image/')),
                ('uploaded_on', models.DateField(auto_now_add=True)),
                ('lastdate', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.user_reg')),
            ],
        ),
    ]
