# Generated by Django 4.2.6 on 2023-11-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_govt_policies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='govt_policies',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Policies/'),
        ),
    ]
