# Generated by Django 4.2.6 on 2023-11-07 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_alter_delivery_agent_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='tip_category',
            fields=[
                ('tip_cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tips',
            fields=[
                ('tip_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(blank=True, null=True, upload_to='image/')),
                ('description', models.TextField(blank=True)),
                ('tip_cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.tip_category')),
            ],
        ),
    ]
