# Generated by Django 4.2.6 on 2023-11-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_tip_category_tips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tips',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
