# Generated by Django 4.2.6 on 2023-11-08 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_tips_farmhouse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tips',
            old_name='tip_cat_id',
            new_name='category',
        ),
    ]
