# Generated by Django 4.2.6 on 2023-11-11 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0023_rename_tip_cat_id_tips_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='rental_category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='rental_product',
            fields=[
                ('machine_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='machinery_images/')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.rental_category')),
                ('farmhouse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.farmhouse_reg')),
            ],
        ),
    ]
