# Generated by Django 4.2.6 on 2023-11-12 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_rental_category_rental_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='rental_request',
            fields=[
                ('req_id', models.AutoField(primary_key=True, serialize=False)),
                ('no_of_days', models.IntegerField()),
                ('requested_on', models.DateField(auto_now_add=True)),
                ('req_status', models.BooleanField(default=True)),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.farmer_reg')),
                ('farmhouse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.farmhouse_reg')),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.rental_product')),
            ],
        ),
    ]
